ADSBackend/Models/School.cs
using ADSBackend.Models.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using ADSBackend.Util;

namespace ADSBackend.Models
{
    public class School
    {
        [Key]
        public int SchoolId { get; set; }

        public int? DivisionId { get; set; }
        public Division Division { get; set; }

        [DisplayName("School Name")]
        public String Name { get; set; }

        [DisplayName("Short Name")]
        [StringLength(12)]
        public String ShortName { get; set; }

        [DisplayName("Abbreviation")]
        [StringLength(3)]
        public String Abbreviation { get; set; }

        [DisplayName("Advisor Name")]
        public String AdvisorName { get; set; }

        [DisplayName("Advisor Email")]
        public String AdvisorEmail { get; set; }

        [DisplayName("Advisor Phone Number")]
        public String AdvisorPhoneNumber { get; set; }

        [DisplayName("Season")]
        public int SeasonId { get; set; }
        public Season Season { get; set; }

        [DisplayName("Join Code")] public string JoinCode { get; set; } = RandomIdGenerator.Generate(8);

        public List<UserSchool> Users { get; set; }
        public List<Player> Players { get; set; }

        [NotMapped]
        public int Wins { get; set; } = 0;
        [NotMapped] 
        public int Losses { get; set; } = 0;
        [NotMapped] 
        public int Ties { get; set; } = 0;
        [NotMapped]
        public double Points
        {
            get
            {
                return Wins + (Ties * 0.5);
            }
        }
    }
}

ADSBackend/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADSBackend.Data;
using ADSBackend.Models;
using ADSBackend.Services;
using Microsoft.AspNetCore.Authorization;

namespace ADSBackend.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SchoolsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly DataService _dataService;

        public SchoolsController(ApplicationDbContext context, DataService dataService)
        {
            _context = context;
            _dataService = dataService;
        }

        // GET: Schools
        public async Task<IActionResult> Index()
        {
            var currentSeason = await _dataService.GetCurrentSeasonId();

            var schools = await _context.School.Where(m => m.SchoolId != 1 && m.SeasonId == currentSeason)
                                               .Include(m => m.Season)
                                               .Include(m => m.Division)
                                               .OrderBy(m => m.Season.StartDate)
                                               .ThenBy(m => m.DivisionId)
                                               .ThenBy(m => m.Name)
                                               .ToListAsync();

            return View(schools);
        }

        public async Task<School> GetModel (int ?id)
        {
            if (id == null)
                return null;

            var school = await _context.School.FirstOrDefaultAsync(m => m.SchoolId == id);
                                              
            if (school == null)
            {
                return null;
            }

            return school;

        }

        // GET: Schools/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            School model = await GetModel(id);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Schools/Create
        public async Task<IActionResult> Create()
        {
            var currentSeason = await _dataService.GetCurrentSeasonId();

            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name", currentSeason);

            ViewBag.Divisions = new SelectList(await _context.Division.Select(x => x).Where(d => d.SeasonId == currentSeason)
                .OrderByDescending(x => x.Name)
                .ToListAsync(), "DivisionId", "Name");

            return View();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SeasonId,DivisionId,SchoolId,Name,ShortName,Abbreviation,AdivisorName,AdvisorEmail,AdvisorPhoneNumber")] School school)
        {
            if (ModelState.IsValid)
            {
                if (school.Abbreviation != null)
                {
                    school.Abbreviation = school.Abbreviation.ToUpper();
                    if (school.Abbreviation.Length > 3)
                        school.Abbreviation = school.Abbreviation.Substring(0, 3);
                }

                _context.Add(school);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        // GET: Schools/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentSeason = await _dataService.GetCurrentSeasonId();

            var school = await _context.School.FindAsync(id);
            if (school == null)
            {
                return NotFound();
            }

            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name");

            ViewBag.Divisions = new SelectList(await _context.Division.Select(x => x)
                .Where(d => d.SeasonId == currentSeason)
                .OrderByDescending(x => x.Name)
                .ToListAsync(), "DivisionId", "Name");

            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SeasonId,DivisionId,SchoolId,Name,ShortName,Abbreviation,AdvisorName,AdvisorEmail,AdvisorPhoneNumber")] School school)
        {
            if (id != school.SchoolId)
            {
                return NotFound();
            }

            var _school = await _context.School.FirstOrDefaultAsync(s => s.SchoolId == id);

            if (_school != null && ModelState.IsValid)
            {
                _school.SeasonId = school.SeasonId;
                _school.DivisionId = school.DivisionId;
                _school.Name = school.Name;
                _school.ShortName = school.ShortName;
                _school.Abbreviation = school.Abbreviation;
                _school.AdvisorName = school.AdvisorName;
                _school.AdvisorEmail = school.AdvisorEmail;
                _school.AdvisorPhoneNumber = school.AdvisorPhoneNumber;

                if (school.Abbreviation != null)
                {
                    _school.Abbreviation = school.Abbreviation.ToUpper();

                    if (school.Abbreviation.Length > 3)
                        school.Abbreviation = school.Abbreviation.Substring(0, 3);

                }

                try
                {
                    _context.Update(_school);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolExists(school.SchoolId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        // GET: Schools/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School
                .FirstOrDefaultAsync(m => m.SchoolId == id);
            if (school == null)
            {
                return NotFound();
            }

            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x).ToListAsync(), "SeasonId", "Name");

            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var school = await _context.School.FindAsync(id);
            _context.School.Remove(school);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolExists(int id)
        {
            return _context.School.Any(e => e.SchoolId == id);
        }
    }
}

ADSBackend/Views/Schools/Create.cshtml
@model ADSBackend.Models.School

@{
    ViewData["Title"] = "Create";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Schools" asp-action="Index">Schools</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>Create</strong>
    </li>
</ol>

<div class="ibox">
<div class="ibox-title"><h4>Create School</h4></div>
<div class="ibox-content">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <select asp-for="SeasonId" asp-items="ViewBag.Seasons" class="form-control"></select>
            </div>
            <div class="form-group">
                <select asp-for="DivisionId" asp-items="ViewBag.Divisions" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortName" class="control-label"></label>
                <input asp-for="ShortName" maxlength="12" class="form-control" />
                <span asp-validation-for="ShortName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abbreviation" class="control-label"></label>
                <input asp-for="Abbreviation" maxlength="3" class="form-control" />
                <span asp-validation-for="Abbreviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdvisorName" class="control-label"></label>
                <input asp-for="AdvisorName" class="form-control" />
                <span asp-validation-for="AdvisorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdvisorEmail" class="control-label"></label>
                <input asp-for="AdvisorEmail" class="form-control" />
                <span asp-validation-for="AdvisorEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdvisorPhoneNumber" class="control-label"></label>
                <input asp-for="AdvisorPhoneNumber" class="form-control" />
                <span asp-validation-for="AdvisorPhoneNumber" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADSBackend/Views/Schools/Delete.cshtml
@model ADSBackend.Models.School

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>School</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SchoolId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ADSBackend/Views/Schools/Details.cshtml
@model ADSBackend.Models.School

@{
    ViewData["Title"] = "Details";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Schools" asp-action="Index">Schools</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>School Details</strong>
    </li>
</ol>

<h2>Details</h2>

<div class="ibox">
    <div class="ibox-title">
        <h4>@Model.Name</h4>
    </div>
    <div class="ibox-content">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ShortName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ShortName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Abbreviation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Abbreviation)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AdvisorName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AdvisorName)
            </dd>
        </dl>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.SchoolId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ADSBackend/Views/Schools/Edit.cshtml
@model ADSBackend.Models.School

@{
    ViewData["Title"] = "Edit";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Schools" asp-action="Index">Schools</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>@Model.Name</strong>
    </li>
</ol>

<h2>Edit</h2>

<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title"><h4>School</h4></div>
            <div class="ibox-content">
                <div class="col-md-4" style="float: none">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="SchoolId"/>
                        <div class="form-group">
                            <select asp-for="SeasonId" asp-items="ViewBag.Seasons" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <select asp-for="DivisionId" asp-items="ViewBag.Divisions" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control"/>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ShortName" class="control-label"></label>
                            <input asp-for="ShortName" maxlength="12" class="form-control"/>
                            <span asp-validation-for="ShortName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Abbreviation" class="control-label"></label>
                            <input asp-for="Abbreviation" maxlength="3" class="form-control"/>

                            <span asp-validation-for="Abbreviation" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="AdvisorName" class="control-label"></label>
                            <input asp-for="AdvisorName" class="form-control"/>
                            <span asp-validation-for="AdvisorName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AdvisorEmail" class="control-label"></label>
                            <input asp-for="AdvisorEmail" class="form-control"/>
                            <span asp-validation-for="AdvisorEmail" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AdvisorPhoneNumber" class="control-label"></label>
                            <input asp-for="AdvisorPhoneNumber" class="form-control" data-mask="(999) 999-9999" placeholder=""/>
                            <span asp-validation-for="AdvisorPhoneNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-success"/>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADSBackend/Views/Schools/Index.cshtml
@model IEnumerable<ADSBackend.Models.School>

@{
    ViewData["Title"] = "Schools";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>Schools</strong>
    </li>
</ol>

<h2>Schools</h2>

<p>
    <a asp-action="Create" class="btn btn-w-m btn-primary">Create New</a>
</p>
<div class="ibox-content">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JoinCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Season.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Division.Name)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="vertical-align: middle">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="vertical-align: middle">
                        <strong>@Html.DisplayFor(modelItem => item.JoinCode)</strong>
                    </td>
                    <td style="vertical-align: middle">
                        @Html.DisplayFor(modelItem => item.Season.Name)
                    </td>
                    <td style="vertical-align: middle">
                        @Html.DisplayFor(modelItem => item.Division.Name)
                    </td>
                    <td style="vertical-align: middle">
                        @await Html.PartialAsync("_CrudOptions", item.SchoolId)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

</div>