ADSBackend/Models/Division.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ADSBackend.Models
{
    public class Division
    {
        [Key]
        public int DivisionId { get; set; }

        [DisplayName("Season")]
        public int? SeasonId { get; set; }
        public Season Season { get; set; }

        public string Name { get; set; }

        public List<School> Schools { get; set; }
    }
}

ADSBackend/Controllers/DivisionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADSBackend.Data;
using ADSBackend.Models;
using Microsoft.AspNetCore.Authorization;
using ADSBackend.Services;

namespace ADSBackend.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DivisionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly DataService _dataService;

        public DivisionsController(ApplicationDbContext context, DataService dataService)
        {
            _context = context;
            _dataService = dataService;
        }

        // GET: Divisions
        public async Task<IActionResult> Index()
        {
            var currentSeason = await _dataService.GetCurrentSeasonId();

            return View(await _context.Division.Where(d => d.SeasonId == currentSeason).ToListAsync());
        }

        // GET: Divisions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var division = await _context.Division
                .FirstOrDefaultAsync(m => m.DivisionId == id);
            if (division == null)
            {
                return NotFound();
            }

            return View(division);
        }

        // GET: Divisions/Create
        public async Task<IActionResult> Create()
        {
            var currentSeason = await _dataService.GetCurrentSeasonId();


            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name", currentSeason);


            return View();
        }

        // POST: Divisions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DivisionId,Name,SeasonId")] Division division)
        {
            var currentSeason = await _dataService.GetCurrentSeasonId();


            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name", currentSeason);


            if (ModelState.IsValid)
            {
                division.SeasonId = currentSeason;

                _context.Add(division);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(division);
        }

        // GET: Divisions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentSeason = await _dataService.GetCurrentSeasonId();

            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name", currentSeason);

            var division = await _context.Division.FindAsync(id);
            if (division == null)
            {
                return NotFound();
            }
            return View(division);
        }

        // POST: Divisions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DivisionId,Name,SeasonId")] Division division)
        {
            if (id != division.DivisionId)
            {
                return NotFound();
            }

            var currentSeason = await _dataService.GetCurrentSeasonId();


            ViewBag.Seasons = new SelectList(await _context.Season.Select(x => x)
                                                                  .OrderByDescending(x => x.StartDate)
                                                                  .ToListAsync(), "SeasonId", "Name", currentSeason);


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(division);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DivisionExists(division.DivisionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(division);
        }

        // GET: Divisions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var division = await _context.Division
                .FirstOrDefaultAsync(m => m.DivisionId == id);
            if (division == null)
            {
                return NotFound();
            }

            return View(division);
        }

        // POST: Divisions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var division = await _context.Division.FindAsync(id);
            _context.Division.Remove(division);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DivisionExists(int id)
        {
            return _context.Division.Any(e => e.DivisionId == id);
        }
    }
}

ADSBackend/Views/Divisions/Create.cshtml
@model ADSBackend.Models.Division

@{
    ViewData["Title"] = "Create";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Divisions" asp-action="Index">Divisions</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>Create Division</strong>
    </li>
</ol>

<h2>Create</h2>

<div class="ibox">
    <div class="ibox-title"><h4>Create Division</h4></div>
    <div class="ibox-content">

        <div class="row">
            <div class="col-md-5">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <select asp-for="SeasonId" asp-items="ViewBag.Seasons" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADSBackend/Views/Divisions/Delete.cshtml
@model ADSBackend.Models.Division

@{
    ViewData["Title"] = "Delete";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li>
        <a asp-controller="Divisions" asp-action="Index">Divisions</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>Delete @Model.Name</strong>
    </li>
</ol>

<h2>Delete</h2>

<div class="ibox">
    <div class="ibox-title"><h4>Are you sure you want to delete this?</h4></div>
    <div class="ibox-content">
        <h4>Division</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="DivisionId" />
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

ADSBackend/Views/Divisions/Details.cshtml
@model ADSBackend.Models.Division

@{
    ViewData["Title"] = "Details";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Divisions" asp-action="Index">Divisions</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>@Model.Name Details</strong>
    </li>
</ol>

<h2>Details</h2>


    <div class="ibox">
        <div class="ibox-content">
            <div class="row">
                <div class="col-lg-5">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                    </dl>
                </div>
            </div>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.DivisionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ADSBackend/Views/Divisions/Edit.cshtml
@model ADSBackend.Models.Division

@{
    ViewData["Title"] = "Edit";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="Divisions" asp-action="Index">Divisions</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>@Model.Name</strong>
    </li>
</ol>

<h2>Edit</h2>

<div class="ibox">
    <div class="ibox-title"><h4>Division</h4></div>
    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-5">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="DivisionId" />
                    <div class="form-group">
                        <select asp-for="SeasonId" asp-items="ViewBag.Seasons" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADSBackend/Views/Divisions/Index.cshtml
@model IEnumerable<ADSBackend.Models.Division>

@{
    ViewData["Title"] = "Index";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a asp-controller="Admin" asp-action="Index">Home</a>
    </li>
    <li class="breadcrumb-item active">
        <strong>Divisions</strong>
    </li>
</ol>

<h2>Divisions</h2>

<p>
    <a asp-action="Create" class="btn btn-w-m btn-primary">Create New</a>
</p>
<div class="ibox">
    <div class="ibox-content">
        <table class="table">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td style="vertical-align: middle">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="vertical-align: middle">
                        @await Html.PartialAsync("_CrudOptions", item.DivisionId)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>